export const TYPES = {
  bug: 'bug',
  dark: 'dark',
  dragon: 'dragon',
  electric: 'electric',
  fairy: 'fairy',
  fighting: 'fighting',
  fire: 'fire',
  flying: 'flying',
  ghost: 'ghost',
  grass: 'grass',
  ground: 'ground',
  ice: 'ice',
  normal: 'normal',
  poison: 'poison',
  psychic: 'psychic',
  rock: 'rock',
  shadow: 'shadow',
  steel: 'steel',
  unknown: 'unknown',
  water: 'water',
}
